/* ============================================================
   TASK 11 — Report Renderer
   Takes a report payload and opens a fully formatted, editable
   report in a new browser tab. Includes Print button.

   Chart images are injected as Blob URLs after the document
   is written to avoid crashing the tab with large base64 strings.
   ============================================================ */

/**
 * Render a TutorDCF valuation report in a new browser tab.
 * @param {Object} payload - Report data from ReportBuilder
 * @param {Object} payload.sections - Text sections keyed by id
 * @param {Array}  payload.charts - Selected chart data [{id, title, imageData}]
 * @param {Object} payload.metrics - { default: [...], additional: [...] }
 * @param {Object} payload.meta - { companyName, reportTitle, date, analystName }
 */
window.TutorDCFReportRenderer = function (payload) {
  'use strict';

  const { sections, charts, metrics, meta } = payload;

  // Collect chart image data separately — keep it OUT of the HTML string
  const chartImageDataList = (charts || []).map(c => c.imageData || '');

  // Build the full HTML document (charts use empty src placeholder)
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${_escHtml(meta.companyName)} Valuation Report — TutorDCF</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
  <style>${_getReportCSS()}</style>
</head>
<body>
  <!-- Print button (hidden in print) -->
  <button class="print-btn" onclick="window.print()">Print / Save PDF</button>

  <div class="report-container">
    <!-- HEADER -->
    <header class="report-header">
      <div class="report-brand">
        <span class="brand-name">Tutor<span class="brand-accent">DCF</span></span>
        <span class="brand-sub">Valuation Report</span>
      </div>
      <div class="report-meta">
        <h1 class="report-title" contenteditable="true">${_escHtml(meta.reportTitle || (meta.companyName + ' Valuation Report'))}</h1>
        <div class="report-meta-row">
          <div class="meta-item">
            <span class="meta-label">Company</span>
            <span class="meta-value">${_escHtml(meta.companyName)}</span>
          </div>
          <div class="meta-item">
            <span class="meta-label">Date</span>
            <span class="meta-value">${_escHtml(meta.date)}</span>
          </div>
          <div class="meta-item">
            <span class="meta-label">Analyst</span>
            <span class="meta-value" contenteditable="true">${_escHtml(meta.analystName || 'Analyst Name')}</span>
          </div>
        </div>
      </div>
    </header>

    <!-- BODY: two-column layout -->
    <div class="report-body">
      <!-- LEFT: Narrative sections (50%) -->
      <div class="report-left">
        ${_renderNarrativeSections(sections)}
      </div>

      <!-- RIGHT: Charts + Metrics (50%) -->
      <div class="report-right">
        <!-- Charts area (top 75%) -->
        <div class="report-charts-area">
          ${_renderChartPlaceholders(charts)}
        </div>

        <!-- Metrics area (bottom 25%) -->
        <div class="report-metrics-area">
          <h3 class="section-label">Valuation Summary</h3>
          <div class="metrics-grid">
            ${_renderMetrics(metrics)}
          </div>
        </div>
      </div>
    </div>

    <!-- FOOTER -->
    <footer class="report-footer">
      <p>Generated by <strong>TutorDCF</strong> &mdash; ${_escHtml(meta.date)}</p>
    </footer>
  </div>
</body>
</html>`;

  // Open in new tab
  const newWindow = window.open('', '_blank');
  if (!newWindow) {
    alert('Please allow popups to generate the report.');
    return;
  }

  newWindow.document.open();
  newWindow.document.write(html);
  newWindow.document.close();

  // Inject chart images as Blob URLs after the document is written.
  // This avoids embedding megabytes of base64 in the HTML string.
  setTimeout(function () {
    var imgs = newWindow.document.querySelectorAll('.chart-img');
    chartImageDataList.forEach(function (dataUri, idx) {
      if (!dataUri || !imgs[idx]) return;
      try {
        var parts = dataUri.split(',');
        var mime = (parts[0].match(/:(.*?);/) || [])[1] || 'image/png';
        var raw = atob(parts[1]);
        var arr = new Uint8Array(raw.length);
        for (var j = 0; j < raw.length; j++) arr[j] = raw.charCodeAt(j);
        var blob = new Blob([arr], { type: mime });
        imgs[idx].src = newWindow.URL.createObjectURL(blob);
      } catch (e) {
        // Fallback: use data URI directly (small charts should be fine)
        imgs[idx].src = dataUri;
      }
    });
  }, 100);

  // ================================================================
  // RENDERING HELPERS
  // ================================================================

  function _renderNarrativeSections(sections) {
    const sectionConfig = [
      { id: 'backgroundCompany',    label: 'Background on Company' },
      { id: 'backgroundSegment',    label: 'Background on Segment' },
      { id: 'financialDiagnostics', label: 'Financial Diagnostics' },
      { id: 'dcfAssumptions',       label: 'DCF Assumptions' },
      { id: 'dcfDiagnostics',       label: 'DCF Diagnostics' },
      { id: 'exitPrice',            label: 'Exit Price' },
    ];

    return sectionConfig.map(cfg => {
      const text = sections[cfg.id] || '';
      return `
        <div class="narrative-section">
          <h3 class="section-label">${_escHtml(cfg.label)}</h3>
          <div class="narrative-content" contenteditable="true">${text ? _escHtml(text).replace(/\n/g, '<br>') : '<em class="placeholder-text">No content provided</em>'}</div>
        </div>`;
    }).join('');
  }

  /**
   * Render chart slots with empty src — images injected after document.write().
   */
  function _renderChartPlaceholders(charts) {
    if (!charts || charts.length === 0) {
      return '<p class="no-data-msg">No charts selected</p>';
    }

    const gridClass = charts.length === 1 ? 'charts-grid-1' :
                      charts.length === 2 ? 'charts-grid-2' :
                      'charts-grid-4';

    return `
      <div class="charts-grid ${gridClass}">
        ${charts.map(chart => `
          <div class="chart-slot">
            <img class="chart-img" src="" alt="${_escHtml(chart.title)}" />
            <p class="chart-caption">${_escHtml(chart.title)}</p>
          </div>
        `).join('')}
      </div>`;
  }

  function _renderMetrics(metrics) {
    const allMetrics = [...(metrics.default || []), ...(metrics.additional || [])];

    return allMetrics.map(m => `
      <div class="metric-card-report">
        <span class="metric-card-label">${_escHtml(m.label)}</span>
        <span class="metric-card-value">${_escHtml(m.formattedValue)}</span>
      </div>
    `).join('');
  }

  // ================================================================
  // ESCAPING
  // ================================================================
  function _escHtml(str) {
    if (!str) return '';
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  // ================================================================
  // CSS
  // ================================================================
  function _getReportCSS() {
    return `
      /* === BASE === */
      * { box-sizing: border-box; margin: 0; padding: 0; }

      html {
        font-size: 14px;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
      }

      body {
        background: #0a0b0d;
        color: #f0f2f7;
        font-family: 'Inter', system-ui, -apple-system, sans-serif;
        line-height: 1.5;
        padding: 0;
        margin: 0;
      }

      /* === PRINT BUTTON === */
      .print-btn {
        position: fixed;
        top: 16px;
        right: 16px;
        z-index: 1000;
        padding: 8px 20px;
        font-family: inherit;
        font-size: 0.8125rem;
        font-weight: 600;
        color: #fff;
        background: #4f8ef7;
        border: none;
        border-radius: 6px;
        cursor: pointer;
        box-shadow: 0 2px 8px rgba(79, 142, 247, 0.3);
        transition: background 0.15s;
      }
      .print-btn:hover { background: #3b7ae0; }

      /* === CONTAINER === */
      .report-container {
        max-width: 1100px;
        margin: 0 auto;
        padding: 32px 24px;
      }

      /* === HEADER === */
      .report-header {
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        gap: 24px;
        padding-bottom: 20px;
        margin-bottom: 24px;
        border-bottom: 2px solid rgba(79, 142, 247, 0.3);
      }

      .report-brand {
        display: flex;
        flex-direction: column;
        gap: 2px;
        flex-shrink: 0;
      }

      .brand-name {
        font-size: 1.5rem;
        font-weight: 800;
        letter-spacing: 0.03em;
        color: #f0f2f7;
      }
      .brand-accent { color: #4f8ef7; }

      .brand-sub {
        font-size: 0.6875rem;
        font-weight: 500;
        letter-spacing: 0.06em;
        color: #5a6278;
        text-transform: uppercase;
      }

      .report-meta { flex: 1; }

      .report-title {
        font-size: 1.25rem;
        font-weight: 700;
        letter-spacing: -0.02em;
        color: #f0f2f7;
        margin-bottom: 8px;
        outline: none;
        border-bottom: 1px dashed transparent;
        padding-bottom: 2px;
      }
      .report-title:focus { border-bottom-color: rgba(79, 142, 247, 0.4); }

      .report-meta-row {
        display: flex;
        gap: 24px;
        flex-wrap: wrap;
      }

      .meta-item {
        display: flex;
        flex-direction: column;
        gap: 1px;
      }

      .meta-label {
        font-size: 0.5625rem;
        font-weight: 600;
        letter-spacing: 0.06em;
        text-transform: uppercase;
        color: #5a6278;
      }

      .meta-value {
        font-size: 0.875rem;
        font-weight: 500;
        color: #9aa3b5;
        outline: none;
      }
      .meta-value[contenteditable]:focus {
        color: #f0f2f7;
        border-bottom: 1px dashed rgba(79, 142, 247, 0.4);
      }

      /* === BODY LAYOUT === */
      .report-body {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 24px;
        align-items: start;
      }

      /* === LEFT: NARRATIVE === */
      .report-left {
        display: flex;
        flex-direction: column;
        gap: 16px;
      }

      .narrative-section {
        background: #111318;
        border: 1px solid rgba(255, 255, 255, 0.06);
        border-radius: 8px;
        padding: 12px 14px;
      }

      .section-label {
        font-size: 0.6875rem;
        font-weight: 700;
        letter-spacing: 0.08em;
        text-transform: uppercase;
        color: #4f8ef7;
        margin-bottom: 6px;
      }

      .narrative-content {
        font-size: 0.8125rem;
        line-height: 1.55;
        color: #9aa3b5;
        min-height: 40px;
        outline: none;
        white-space: pre-wrap;
      }
      .narrative-content:focus {
        color: #f0f2f7;
      }
      .placeholder-text {
        color: #5a6278;
        font-style: italic;
      }

      /* === RIGHT: CHARTS + METRICS === */
      .report-right {
        display: flex;
        flex-direction: column;
        gap: 16px;
      }

      .report-charts-area {
        flex: 3;
      }

      .report-metrics-area {
        flex: 1;
        background: #111318;
        border: 1px solid rgba(255, 255, 255, 0.06);
        border-radius: 8px;
        padding: 12px 14px;
      }

      /* Charts grid */
      .charts-grid {
        display: grid;
        gap: 10px;
      }
      .charts-grid-1 { grid-template-columns: 1fr; }
      .charts-grid-2 { grid-template-columns: 1fr 1fr; }
      .charts-grid-4 { grid-template-columns: 1fr 1fr; }

      .chart-slot {
        background: #111318;
        border: 1px solid rgba(255, 255, 255, 0.06);
        border-radius: 8px;
        padding: 8px;
        display: flex;
        flex-direction: column;
        gap: 4px;
      }

      .chart-img {
        width: 100%;
        height: auto;
        border-radius: 4px;
        display: block;
        min-height: 80px;
        background: #181b22;
      }

      .chart-caption {
        font-size: 0.6875rem;
        font-weight: 500;
        color: #5a6278;
        text-align: center;
      }

      .no-data-msg {
        font-size: 0.8125rem;
        color: #5a6278;
        font-style: italic;
        text-align: center;
        padding: 24px 0;
      }

      /* Metrics grid */
      .metrics-grid {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 8px;
      }

      .metric-card-report {
        background: #181b22;
        border: 1px solid rgba(255, 255, 255, 0.06);
        border-radius: 6px;
        padding: 8px 10px;
        display: flex;
        flex-direction: column;
        gap: 2px;
      }

      .metric-card-label {
        font-size: 0.5625rem;
        font-weight: 600;
        letter-spacing: 0.06em;
        text-transform: uppercase;
        color: #5a6278;
      }

      .metric-card-value {
        font-family: 'SF Mono', 'Fira Code', 'Cascadia Code', 'Roboto Mono', monospace;
        font-size: 0.9375rem;
        font-weight: 700;
        font-variant-numeric: tabular-nums;
        color: #f0f2f7;
      }

      /* === FOOTER === */
      .report-footer {
        margin-top: 32px;
        padding-top: 12px;
        border-top: 1px solid rgba(255, 255, 255, 0.06);
        text-align: center;
      }
      .report-footer p {
        font-size: 0.6875rem;
        color: #5a6278;
      }

      /* === PRINT STYLES === */
      @media print {
        .print-btn { display: none !important; }

        body {
          background: #fff !important;
          color: #111 !important;
          font-size: 11px;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }

        .report-container {
          max-width: 100%;
          padding: 0;
        }

        .report-header {
          border-bottom-color: #333;
        }

        .brand-name { color: #111; }
        .brand-accent { color: #2563eb; }
        .brand-sub { color: #666; }

        .report-title,
        .meta-value,
        .narrative-content { color: #111; }
        .meta-label,
        .section-label { color: #444; }
        .section-label { color: #2563eb; }

        .narrative-section,
        .chart-slot,
        .report-metrics-area {
          background: #fafafa !important;
          border-color: #ddd !important;
        }

        .metric-card-report {
          background: #f5f5f5 !important;
          border-color: #ddd !important;
        }
        .metric-card-label { color: #555; }
        .metric-card-value { color: #111; }

        .chart-caption { color: #555; }
        .no-data-msg { color: #888; }
        .placeholder-text { color: #999; }

        .report-footer {
          border-top-color: #ddd;
        }
        .report-footer p { color: #888; }

        /* Editable fields: remove dashed borders */
        [contenteditable] {
          border: none !important;
        }

        /* Portrait orientation */
        @page {
          size: letter portrait;
          margin: 0.6in;
        }
      }

      /* === RESPONSIVE === */
      @media (max-width: 768px) {
        .report-body {
          grid-template-columns: 1fr;
        }
        .report-header {
          flex-direction: column;
        }
      }
    `;
  }
};
